atestados = [
    
    {"Nome": "João", 
     "Turma": '2°', 
     "RA": 100001, 
     "Tipo": 'Maternidade', 
     "Inicio": '12.03.2025', 
     "Fim": 'xx.xx.xxxx', 
     "Horas": 'xx:xx - xx:xx', 
     "Status": 'Pendente', 
     "Motivo": 'Recusado por erro de dados', 
     "Comprovante": "ID do comprovante", 
     "ID": 1},
    
    {"Nome": "Yuri",
     "Turma": '3°',
     "RA": 100002,
     "Tipo": 'Cirurgia',
     "Inicio": '13.03.2025',
     "Fim": 'xx.xx.xxxx', 
     "Horas": 'xx:xx - xx:xx',
     "Status": True,
     "Motivo": '-',
     "Comprovante": "ID do comprovante",
     "ID": 2},
    
    {"Nome": "Leonardo",
     "Turma": '1°',
     "RA": 100003,
     "Tipo": 'Incapacidade',
     "Inicio": '14.03.2025',
     "Fim": 'xx.xx.xxxx', 
     "Horas": 'xx:xx - xx:xx',
     "Status": False,
     "Motivo": '-',
     "Comprovante": "ID do comprovante",
     "ID": 3},
    
    {"Nome": "Lucas",
     "Turma": '1°',
     "RA": 100004,
     "Tipo": 'Consulta Médica',
     "Inicio": 'xx.xx.xxxx',
     "Fim": 'xx.xx.xxxx', 
     "Horas": 'xx:xx - xx:xx',
     "Status": True,
     "Motivo": '-',
     "Comprovante": "ID do comprovante",
     "ID": 4},
    
    {"Nome": "Lydia",
     "Turma": '1°',
     "RA": 100005,
     "Tipo": 'Incapacidade',
     "Inicio": 'xx.xx.xxxx',
     "Fim": 'xx.xx.xxxx', 
     "Horas": 'xx:xx - xx:xx',
     "Status": True,
     "Motivo": '-',
     "Comprovante": "ID do comprovante",
     "ID": 5},
    
    {"Nome": "Jessica",
     "Turma": '1°',
     "RA": 100006,
     "Tipo": 'Consulta Médica',
     "Inicio": 'xx.xx.xxxx',
     "Fim": 'xx.xx.xxxx', 
     "Horas": 'xx:xx - xx:xx',
     "Status": 'Pendente',
     "Motivo": '-',
     "Comprovante": "ID do comprovante",
     "ID": 6},
    
    {"Nome": "Alice",
     "Turma": '1°',
     "RA": 100007,
     "Tipo": 'Consulta Médica',
     "Inicio": 'xx.xx.xxxx',
     "Fim": 'xx.xx.xxxx', 
     "Horas": 'xx:xx - xx:xx',
     "Status": True,
     "Motivo": '-',
     "Comprovante": "ID do comprovante",
     "ID": 7},
    
    {"Nome": "Beatriz",
     "Turma": '1°',
     "RA": 100008,
     "Tipo": 'Consulta Médica',
     "Inicio": 'xx.xx.xxxx',
     "Fim": 'xx.xx.xxxx', 
     "Horas": 'xx:xx - xx:xx',
     "Status": True,
     "Motivo": '-',
     "Comprovante": "ID do comprovante",
     "ID": 8},
    
    {"Nome": "João",
     "Turma": '2°',
     "RA": 100001,
     "Tipo": 'Afastamento',
     "Inicio": 'xx.xx.xxxx',
     "Fim": 'xx.xx.xxxx', 
     "Horas": 'xx:xx - xx:xx',
     "Status": 'Pendente',
     "Motivo": '-',
     "Comprovante": "ID do comprovante",
     "ID": 9},
    
    {"Nome": "Ana",
     "Turma": '3°',
     "RA": 100010,
     "Tipo": 'Cirurgia',
     "Inicio": 'xx.xx.xxxx',
     "Fim": 'xx.xx.xxxx', 
     "Horas": 'xx:xx - xx:xx',
     "Status": 'Pendente',
     "Motivo": '-',
     "Comprovante": "ID do comprovante",
     "ID": 2}
]

